name: Build Workshop

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - masters

jobs:
  build:
    runs-on: ubuntu-latest
    container: rocker/verse:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install /qcbsRworkshops
        run: |
            install.packages('remotes')
            remotes::install_github("inSileco/rowlbot")
        shell: Rscript {0}
      - name: Build workshop 
        run: Rscript -e 'qcbsRworkshops::build_workshops(update_template = TRUE, pdf = TRUE, script = TRUE)'
      - name: Deploy workshop to gh-pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./public
